// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4-vnLC_AljSNGmlc3cOrYdF4Ys-CebJE',
    appId: '1:1023280359844:web:1a12bd2417f01740d2b931',
    messagingSenderId: '1023280359844',
    projectId: 'arama',
    authDomain: 'arama.firebaseapp.com',
    storageBucket: 'arama.appspot.com',
    measurementId: 'G-BCV17MN91S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdn5uJSKjtugRPvrYSwM7v3zY5cLrrNPw',
    appId: '1:1023280359844:android:736e9744071b7c57d2b931',
    messagingSenderId: '1023280359844',
    projectId: 'arama',
    storageBucket: 'arama.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlOqpDlg827rwEtv1KalQRk0MgLLFKtSM',
    appId: '1:1023280359844:ios:b6b8121bf2fc0a99d2b931',
    messagingSenderId: '1023280359844',
    projectId: 'arama',
    storageBucket: 'arama.appspot.com',
    iosBundleId: 'com.example.aramaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlOqpDlg827rwEtv1KalQRk0MgLLFKtSM',
    appId: '1:1023280359844:ios:7b76c6e947bb75b7d2b931',
    messagingSenderId: '1023280359844',
    projectId: 'arama',
    storageBucket: 'arama.appspot.com',
    iosBundleId: 'com.example.aramaApp.RunnerTests',
  );
}
